name: Build Kurdish80p Tweak

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        brew install dpkg ldid

    - name: Setup Theos Framework & Official SDKs
      run: |
        # کڵۆنکردنی فەرمی فڕەیموۆرکی تیۆس
        git clone --recursive https://github.com/theos/theos.git $HOME/theos
        
        # سڕینەوەی فۆڵدەری کۆنی sdks ئەگەر هەبێت
        rm -rf $HOME/theos/sdks
        
        # دابەزاندنی تەواوی وەشانی فەرمی SDK کانی ئایفۆن بە خێراترین شێوە (Shallow Clone)
        git clone --depth 1 https://github.com/theos/sdks.git $HOME/theos/sdks

    - name: Compile Package
      run: |
        export THEOS=$HOME/theos
        make package FINALPACKAGE=1

    - name: Upload DEB Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kurdish80p-Tweak
        path: packages/*.deb
